### ISSUE TITLE
Windows Docker (Toolbox) Service lolibrary_www Start Error - Mount a directory onto a file error.

### ISSUE THREAD

**Issue by ghost** [lolibrary/lolibrary#19]
Dear Lolibrary Community,

I tried to build and run the Lolibrary on Windows 10 x64, unfortunately I got the following error message:

![docker error](https://user-images.githubusercontent.com/8598762/50730175-ecd0ca80-1146-11e9-848b-efcc36cf7ad7.PNG)

ERROR: for lolibrary_www.lolibrary.test_1 
	Cannot start service www.lolibrary.test:
	OCI runtime create failed:
	container_linux.go:348:
	starting container process caused "process_linux.go:402:
	container init caused \"rootfs_linux.go:58: 
	mounting \\\"/host_mnt/e/lolibrary/.env\\\" 
	to rootfs \\\"/var/lib/docker/overlay2/c64e98c6fd0e2bc401e80ace3e12cf2df04f203e0d693e80ff3eccf238f26e3d/merged\\\" 
	at \\\"/var/lib/docker/overlay2/c64e98c6fd0e2bc401e80ace3e12cf2df04f203e0d693e80ff3eccf238f26e3d/merged/secrets/environment/.env\\\" 
	caused \\\"not a directory\\\"\"": 
	unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

It fails when trying to start lolibrary_www.lolibrary.test_1 service.

Besides that I created a Powershell Script to make it possible to install the required things on Windows.
And everything install (rename .var.example, certificate, docker pull) as required works and is tested on Windows 10 (script as file can be seen on my fork).

![powershell install script](https://user-images.githubusercontent.com/8598762/50730193-5bae2380-1147-11e9-996e-0b0385cbb221.PNG)

I do currently not understand what the problem is and what the cause is. I did already Googled about it, but not with any success.

https://groups.google.com/forum/#!topic/awx-project/2F5dJIdmdXw
https://forums.docker.com/t/solved-error-for-httpd-oci-runtime-error-rootfs-linux-go-53-mounting-to-rootfs-caused-not-a-directory/17509/3
https://community.tyk.io/t/how-can-i-fix-the-error-mounting-caused-not-a-directory-when-using-docker-compose/1068/5

Drivers are shared

![shared drive](https://user-images.githubusercontent.com/8598762/50730190-2a355800-1147-11e9-98d4-7ad6f8fb07c0.PNG)

Docker Version

![docker version](https://user-images.githubusercontent.com/8598762/50730204-decf7980-1147-11e9-828d-b5a46b21abe3.PNG)

Even if I tried it with docker Toolbox but unfortunately it is raising approximately the same error, but now when it is trying to start the proxy.

![docker toolbox](https://user-images.githubusercontent.com/8598762/50730410-67044d80-114d-11e9-8faa-9782bbf2c24d.PNG)

I hope you can help.

Yours sincerely,
Chun

**Comment by ameliaikeda** [comment]
Slightly stumped around this; I don't actually have a windows 10 pro install to test this repo on windows, so I'm not entirely sure how to go about fixing this :/

In the meantime, you might be able to run this in a linux VM? It's not ideal, but I'll see if I can debug this when I have the time!

**Comment by ChunCVL** [comment]
Dear Amelia,

I will try to set it up with with Debian 9.6 in VM.
and I will let you know the results.

~Chun

**Comment by ChunCVL** [comment]
Dear Amelia,

Thank you for your tip 😊.

It works under Debian 9.6 x64 👌 (Tested in VirtualBox v5.2.22r 126460 (Qt5.6.2))
I am making bash installation script (apt-get based; sorry yum/pacman/etc. 😅 ), so that everyone can develop it also under Linux ☀️ (sorry other Unix users 😅 ).
And if the script is perfect, I will send a pull request 🌊.
For the time being the script can be found under my fork 🎵  https://github.com/ChunCVL/lolibrary

~Chun
